"""validate the reverse-engineered decoder against the official Oura API.

decodes a bug-report zip / btsnoop into daily summaries (pure summarize), pulls
the same window from the Oura API (pure build), and diffs the directly-comparable
fields per overlapping date. writes docs/VALIDATION.md — the proof artifact that
this is genuine reverse engineering, not an API wrapper.

  VITALDECK_OURA_TOKEN=... python -m tools.validate <bugreport.zip|btsnoop> [--days 30]

skin temperature is intentionally excluded: the API exposes a deviation we map
onto a nominal absolute, so it isn't directly comparable to the ring's raw temp.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Optional

from vitaldeck import config, summarize
from vitaldeck.ingest import decode as decode_mod
from vitaldeck.ingest import oura_api
from vitaldeck.ingest import pull_snoop

# (field, unit, decimals) for the top-level comparable metrics
SCALAR_FIELDS = [
    ("hrv_rmssd", "ms", 0),
    ("resting_hr", "bpm", 0),
    ("spo2_avg", "%", 1),
    ("resp_rate", "rpm", 1),
    ("sleep_min", "min", 0),
    ("sleep_efficiency", "%", 0),
]
STAGE_FIELDS = ["deep_min", "rem_min", "light_min", "awake_min"]


def _stages(row: dict[str, Any]) -> dict[str, Any]:
    """parsing stage_breakdown_json off a daily dict, tolerating str|dict|None."""
    raw = row.get("stage_breakdown_json")
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        try:
            return json.loads(raw)
        except ValueError:
            return {}
    return {}


def _by_date(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {r["date"]: r for r in rows if r.get("date")}


def diff_rows(
    snoop: dict[str, dict[str, Any]],
    api: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    """pure diff: one row per (date, field) where BOTH sides have a value."""
    out: list[dict[str, Any]] = []
    for date in sorted(set(snoop) & set(api)):
        s, a = snoop[date], api[date]
        s_stages, a_stages = _stages(s), _stages(a)
        for field, unit, digits in SCALAR_FIELDS:
            _maybe(out, date, field, unit, digits, s.get(field), a.get(field))
        for field in STAGE_FIELDS:
            _maybe(out, date, field, "min", 0, s_stages.get(field), a_stages.get(field))
    return out


def _maybe(out, date, field, unit, digits, sv, av) -> None:
    if sv is None or av is None:
        return
    try:
        sv, av = float(sv), float(av)
    except (TypeError, ValueError):
        return
    out.append({
        "date": date, "field": field, "unit": unit, "digits": digits,
        "decoded": sv, "api": av, "delta": sv - av,
    })


def _resolve_btsnoop(path: Path) -> Path:
    if path.suffix.lower() == ".zip":
        return pull_snoop.extract_btsnoop(path)
    return path


def _render(rows: list[dict[str, Any]]) -> str:
    lines = [
        "# VitalDeck — decoder validation",
        "",
        "Clean-room BLE decoder (`open_ring replay` over the phone's Bluetooth snoop log) vs the",
        "official Oura API, same nights. Skin temperature is omitted (the API exposes a deviation,",
        "not an absolute). Generated by `python -m tools.validate`.",
        "",
        "| date | field | decoded | api | Δ |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        d = r["digits"]
        lines.append(
            f"| {r['date']} | {r['field']} | {r['decoded']:.{d}f}{r['unit']} | "
            f"{r['api']:.{d}f}{r['unit']} | {r['delta']:+.{d}f} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="validate the snoop-log decoder against the Oura API")
    ap.add_argument("capture", help="bugreport .zip or raw btsnoop_hci.log")
    ap.add_argument("--days", type=int, default=30)
    args = ap.parse_args(argv)

    token = config.OURA_TOKEN
    if not token:
        print("set VITALDECK_OURA_TOKEN to validate against the api", file=sys.stderr)
        return 2

    cap = Path(args.capture)
    if not cap.exists():
        print(f"capture not found: {cap}", file=sys.stderr)
        return 2

    try:
        records = list(decode_mod.decode_capture(_resolve_btsnoop(cap)))
    except (pull_snoop.PullError, decode_mod.DecodeError) as exc:
        print(f"decode failed: {exc}", file=sys.stderr)
        return 1
    snoop = _by_date(summarize.summarize_records(records)["daily"])

    try:
        api = _by_date(oura_api.build(oura_api.fetch(token, args.days))["daily"])
    except oura_api.OuraError as exc:
        print(f"oura fetch failed: {exc}", file=sys.stderr)
        return 1

    rows = diff_rows(snoop, api)
    if not rows:
        print(
            "no overlapping date/field pairs — does the capture's night overlap the api window, "
            "and did replay decode the nightly metrics?",
            file=sys.stderr,
        )
        return 1

    report = _render(rows)
    out_path = config.REPO_DIR / "docs" / "VALIDATION.md"
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report, encoding="utf-8")
        print(f"wrote {out_path}")
    except OSError as exc:
        print(f"could not write {out_path}: {exc}", file=sys.stderr)

    print()
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
